services:
  - type: web
    name: taskmanager-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    pythonVersion: "3.12.3"
